# Generated by Django 3.0.2 on 2020-01-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_rates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizrate',
            old_name='score',
            new_name='rate',
        ),
    ]
